package Table.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new BaseCoceptComment_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new RootConcept_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Rule_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new TestCase_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new TestCaseComment_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new TestSuite_Editor());
      case 6:
        return Collections.<ConceptEditor>singletonList(new Variable_Editor());
      case 7:
        return Collections.<ConceptEditor>singletonList(new VariableValue_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new TestSuite_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new VariableValue_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efedc804L), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efedc887L), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c18L), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c1dL), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c27L), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c2eL), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c2fL), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c32L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c2eL), MetaIdFactory.conceptId(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c32L)).seal();
}
