package Table.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.AbstractIntentionDescriptor;
import jetbrains.mps.openapi.intentions.IntentionFactory;
import java.util.Collection;
import jetbrains.mps.openapi.intentions.IntentionExecutable;
import jetbrains.mps.openapi.intentions.Kind;
import jetbrains.mps.smodel.SNodePointer;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;
import java.util.Collections;
import jetbrains.mps.intentions.AbstractIntentionExecutable;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.AttributeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.IAttributeDescriptor;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.openapi.intentions.IntentionDescriptor;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public final class TestCase_AddComment_Intention extends AbstractIntentionDescriptor implements IntentionFactory {
  private Collection<IntentionExecutable> myCachedExecutable;
  public TestCase_AddComment_Intention() {
    super(Kind.NORMAL, false, new SNodePointer("r:9359af2e-dc93-4ef4-b866-2cccb9dc01a7(Table.intentions)", "4786391186599439123"));
  }
  @Override
  public String getPresentation() {
    return "TestCase_AddComment";
  }
  @Override
  public boolean isApplicable(final SNode node, final EditorContext editorContext) {
    return true;
  }
  @Override
  public boolean isSurroundWith() {
    return false;
  }
  public Collection<IntentionExecutable> instances(final SNode node, final EditorContext context) {
    if (myCachedExecutable == null) {
      myCachedExecutable = Collections.<IntentionExecutable>singletonList(new IntentionImplementation());
    }
    return myCachedExecutable;
  }
  /*package*/ final class IntentionImplementation extends AbstractIntentionExecutable {
    public IntentionImplementation() {
    }
    @Override
    public String getDescription(final SNode node, final EditorContext editorContext) {
      return (((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.TestCaseComment$zW)) == null) ? "Add" : "Remove")) + " Comment";
    }
    @Override
    public void execute(final SNode node, final EditorContext editorContext) {
      if ((AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.TestCaseComment$eH)) == null)) {
        AttributeOperations.createAndSetAttrbiute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.TestCaseComment$eH), CONCEPTS.TestCaseComment$eH);
      } else {
        SNodeOperations.deleteNode(AttributeOperations.getAttribute(node, new IAttributeDescriptor.NodeAttribute(CONCEPTS.TestCaseComment$eH)));
      }
    }
    @Override
    public IntentionDescriptor getDescriptor() {
      return TestCase_AddComment_Intention.this;
    }
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TestCaseComment$zW = MetaAdapterFactory.getConcept(0x47a015d346f64146L, 0xb38ba6894b8669ceL, 0x41d3cf74efea1c27L, "Table.structure.TestCaseComment");
    /*package*/ static final SConcept TestCaseComment$eH = MetaAdapterFactory.getConcept(0x2d56439e634d4d25L, 0x9d30963e89ecda48L, 0x1366697588b89163L, "de.slisson.mps.tables.demolang.structure.TestCaseComment");
  }
}
